<?php

use Illuminate\Database\Seeder;

use Carbon\Carbon;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $ing = [
            ['id' => '1', 'iName' =>'Curcumin', 'iType' => 1, 'eNumber' => 'E100', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '2', 'iName' =>'Riboflavin', 'iType' => 1, 'eNumber' => 'E101', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '3', 'iName' =>'Tartrazine', 'iType' => 1, 'eNumber' => 'E102', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '4', 'iName' =>'Chrysoidine', 'iType' => 1, 'eNumber' => 'E103', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '5', 'iName' =>'Quinoline Yellow WS', 'iType' => 1, 'eNumber' => 'E104', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '6', 'iName' =>'Fast yellow AB', 'iType' => 1, 'eNumber' => 'E105', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '7', 'iName' =>'Yellow 2G', 'iType' => 1, 'eNumber' => 'E107', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '8', 'iName' =>'Sunset Yellow FCF', 'iType' => 1, 'eNumber' => 'E110', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '9', 'iName' =>'Amylase', 'iType' => 1, 'eNumber' => 'E1100', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '10', 'iName' =>'Protease', 'iType' => 1, 'eNumber' => 'E1101', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '11', 'iName' =>'Invertase', 'iType' => 1, 'eNumber' => 'E1103', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '12', 'iName' =>'Lysozyme', 'iType' => 1, 'eNumber' => 'E1105', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '13', 'iName' =>'Carminic acid', 'iType' => 1, 'eNumber' => 'E120', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '14', 'iName' =>'Polydextrose', 'iType' => 1, 'eNumber' => 'E1200', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '15', 'iName' =>'Polyvinylpyrrolidone', 'iType' => 1, 'eNumber' => 'E1201', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '16', 'iName' =>'Azorubine', 'iType' => 1, 'eNumber' => 'E122', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '17', 'iName' =>'Amaranth (dye)', 'iType' => 1, 'eNumber' => 'E123', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '18', 'iName' =>'Ponceau 4R', 'iType' => 1, 'eNumber' => 'E124', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '19', 'iName' =>'Erythrosine', 'iType' => 1, 'eNumber' => 'E127', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '20', 'iName' =>'Red 2G', 'iType' => 1, 'eNumber' => 'E128', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '21', 'iName' =>'Allura Red AC', 'iType' => 1, 'eNumber' => 'E129', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '22', 'iName' =>'Patent Blue V', 'iType' => 1, 'eNumber' => 'E131', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '23', 'iName' =>'Indigo carmine', 'iType' => 1, 'eNumber' => 'E132', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '24', 'iName' =>'Brilliant Blue FCF', 'iType' => 1, 'eNumber' => 'E133', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '25', 'iName' =>'Chlorophyll a', 'iType' => 1, 'eNumber' => 'E140', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '26', 'iName' =>'Dextrin', 'iType' => 1, 'eNumber' => 'E1400', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '27', 'iName' =>'Modified starch', 'iType' => 1, 'eNumber' => 'E1401', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '28', 'iName' =>'Oxidized Starch', 'iType' => 1, 'eNumber' => 'E1404', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '29', 'iName' =>'Chlorophyllin', 'iType' => 1, 'eNumber' => 'E141', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '30', 'iName' =>'Mono starch Phosphate', 'iType' => 1, 'eNumber' => 'E1410', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '31', 'iName' =>'Distarch phosphate', 'iType' => 1, 'eNumber' => 'E1412', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '32', 'iName' =>'Phosphated distarch phosphate', 'iType' => 1, 'eNumber' => 'E1413', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '33', 'iName' =>'Green S', 'iType' => 1, 'eNumber' => 'E142', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '34', 'iName' =>'Acetylated Starch', 'iType' => 1, 'eNumber' => 'E1420', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '35', 'iName' =>'Acetylated distarch adipate', 'iType' => 1, 'eNumber' => 'E1422', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '36', 'iName' =>'Hydroxypropyl distarch phosphate', 'iType' => 1, 'eNumber' => 'E1442', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '37', 'iName' =>'Starch Sodium Octenyl Succinate', 'iType' => 1, 'eNumber' => 'E1450', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '38', 'iName' =>'Acetylated Oxidized Starch', 'iType' => 1, 'eNumber' => 'E1451', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '39', 'iName' =>'Caramel color', 'iType' => 1, 'eNumber' => 'E150', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '40', 'iName' =>'Triethyl citrate', 'iType' => 1, 'eNumber' => 'E1505', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '41', 'iName' =>'Brilliant Black BN', 'iType' => 1, 'eNumber' => 'E151', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '42', 'iName' =>'Triacetin', 'iType' => 1, 'eNumber' => 'E1518', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '43', 'iName' =>'Propylene glycol', 'iType' => 1, 'eNumber' => 'E1520', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '44', 'iName' =>'Black carbon', 'iType' => 1, 'eNumber' => 'E153', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '45', 'iName' =>'Brown FK', 'iType' => 1, 'eNumber' => 'E154', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '46', 'iName' =>'Brown HT', 'iType' => 1, 'eNumber' => 'E155', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '47', 'iName' =>'Beta carotene', 'iType' => 1, 'eNumber' => 'E160a', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '48', 'iName' =>'Annatto', 'iType' => 1, 'eNumber' => 'E160b', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '49', 'iName' =>'Capsanthin', 'iType' => 1, 'eNumber' => 'E160c', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '50', 'iName' =>'Lycopene', 'iType' => 1, 'eNumber' => 'E160d', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '51', 'iName' =>'Apocarotenal', 'iType' => 1, 'eNumber' => 'E160e', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '52', 'iName' =>'Food orange 7', 'iType' => 1, 'eNumber' => 'E160f', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '53', 'iName' =>'Flavoxanthin', 'iType' => 1, 'eNumber' => 'E161a', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '54', 'iName' =>'Lutein', 'iType' => 1, 'eNumber' => 'E161b', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '55', 'iName' =>'Cryptoxanthin', 'iType' => 1, 'eNumber' => 'E161c', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '56', 'iName' =>'Rubixanthin', 'iType' => 1, 'eNumber' => 'E161d', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '57', 'iName' =>'Violaxanthin', 'iType' => 1, 'eNumber' => 'E161e', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '58', 'iName' =>'Rhodoxanthin', 'iType' => 1, 'eNumber' => 'E161f', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '59', 'iName' =>'Canthaxanthin', 'iType' => 1, 'eNumber' => 'E161g', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '60', 'iName' =>'Betanin', 'iType' => 1, 'eNumber' => 'E162', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '61', 'iName' =>'Anthocyanin', 'iType' => 1, 'eNumber' => 'E163', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '62', 'iName' =>'Calcium carbonate', 'iType' => 1, 'eNumber' => 'E170', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '63', 'iName' =>'Titanium dioxide', 'iType' => 1, 'eNumber' => 'E171', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '64', 'iName' =>'Iron oxide', 'iType' => 1, 'eNumber' => 'E172', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '65', 'iName' =>'Aluminium', 'iType' => 1, 'eNumber' => 'E173', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '66', 'iName' =>'Silver', 'iType' => 1, 'eNumber' => 'E174', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '67', 'iName' =>'Gold', 'iType' => 1, 'eNumber' => 'E175', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '68', 'iName' =>'Lithol rubine BK', 'iType' => 1, 'eNumber' => 'E180', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '69', 'iName' =>'Sorbic acid', 'iType' => 1, 'eNumber' => 'E200', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '70', 'iName' =>'Sodium sorbate', 'iType' => 1, 'eNumber' => 'E201', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '71', 'iName' =>'Potassium sorbate', 'iType' => 1, 'eNumber' => 'E202', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '72', 'iName' =>'Calcium sorbate', 'iType' => 1, 'eNumber' => 'E203', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '73', 'iName' =>'Benzoic acid', 'iType' => 1, 'eNumber' => 'E210', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '74', 'iName' =>'Sodium benzoate', 'iType' => 1, 'eNumber' => 'E211', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '75', 'iName' =>'Potassium benzoate', 'iType' => 1, 'eNumber' => 'E212', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '76', 'iName' =>'Calcium benzoate', 'iType' => 1, 'eNumber' => 'E213', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '77', 'iName' =>'Ethylparaben', 'iType' => 1, 'eNumber' => 'E214', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '78', 'iName' =>'Ethylparaben', 'iType' => 1, 'eNumber' => 'E215', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '79', 'iName' =>'Propylparaben', 'iType' => 1, 'eNumber' => 'E216', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '80', 'iName' =>'Propylparaben', 'iType' => 1, 'eNumber' => 'E217', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '81', 'iName' =>'Methylparaben', 'iType' => 1, 'eNumber' => 'E218', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '82', 'iName' =>'Sodium methylparaben', 'iType' => 1, 'eNumber' => 'E219', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '83', 'iName' =>'Sulphur dioxide', 'iType' => 1, 'eNumber' => 'E220', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '84', 'iName' =>'Sodium sulphite', 'iType' => 1, 'eNumber' => 'E221', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '85', 'iName' =>'Sodium bisulfite', 'iType' => 1, 'eNumber' => 'E222', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '86', 'iName' =>'Sodium metabisulphite', 'iType' => 1, 'eNumber' => 'E223', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '87', 'iName' =>'Potassium metabisulphite', 'iType' => 1, 'eNumber' => 'E224', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '88', 'iName' =>'Calcium sulfite', 'iType' => 1, 'eNumber' => 'E226', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '89', 'iName' =>'Calcium bisulfite', 'iType' => 1, 'eNumber' => 'E227', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '90', 'iName' =>'Potassium bisulfite', 'iType' => 1, 'eNumber' => 'E228', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '91', 'iName' =>'Biphenyl', 'iType' => 1, 'eNumber' => 'E230', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '92', 'iName' =>'2-Phenylphenol', 'iType' => 1, 'eNumber' => 'E231', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '93', 'iName' =>'Sodium orthophenyl phenol', 'iType' => 1, 'eNumber' => 'E232', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '94', 'iName' =>'Tiabendazole', 'iType' => 1, 'eNumber' => 'E233', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '95', 'iName' =>'Nisin', 'iType' => 1, 'eNumber' => 'E234', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '96', 'iName' =>'Natamycin', 'iType' => 1, 'eNumber' => 'E235', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '97', 'iName' =>'Hexamine', 'iType' => 1, 'eNumber' => 'E239', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '98', 'iName' =>'Dimethyl dicarbonate', 'iType' => 1, 'eNumber' => 'E242', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '99', 'iName' =>'Potassium nitrate', 'iType' => 1, 'eNumber' => 'E249', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '100', 'iName' =>'Sodium nitrite', 'iType' => 1, 'eNumber' => 'E250', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '101', 'iName' =>'Sodium nitrate', 'iType' => 1, 'eNumber' => 'E251', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '102', 'iName' =>'Potassium nitrate', 'iType' => 1, 'eNumber' => 'E252', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '103', 'iName' =>'Acetic acid', 'iType' => 1, 'eNumber' => 'E260', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '104', 'iName' =>'Potassium acetate', 'iType' => 1, 'eNumber' => 'E261', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '105', 'iName' =>'Sodium acetate', 'iType' => 1, 'eNumber' => 'E262', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '106', 'iName' =>'Calcium acetate', 'iType' => 1, 'eNumber' => 'E263', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '107', 'iName' =>'Lactic acid', 'iType' => 1, 'eNumber' => 'E270', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '108', 'iName' =>'Propionic acid', 'iType' => 1, 'eNumber' => 'E280', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '109', 'iName' =>'Sodium propionate', 'iType' => 1, 'eNumber' => 'E281', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '110', 'iName' =>'Calcium propanoate', 'iType' => 1, 'eNumber' => 'E282', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '111', 'iName' =>'Potassium propanoate', 'iType' => 1, 'eNumber' => 'E283', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '112', 'iName' =>'Boric acid', 'iType' => 1, 'eNumber' => 'E284', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '113', 'iName' =>'Borax', 'iType' => 1, 'eNumber' => 'E285', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '114', 'iName' =>'Carbon dioxide', 'iType' => 1, 'eNumber' => 'E290', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '115', 'iName' =>'Malic acid', 'iType' => 1, 'eNumber' => 'E296', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '116', 'iName' =>'Fumaric acid', 'iType' => 1, 'eNumber' => 'E297', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '117', 'iName' =>'Ascorbic acid', 'iType' => 1, 'eNumber' => 'E300', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '118', 'iName' =>'Sodium ascorbate', 'iType' => 1, 'eNumber' => 'E301', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '119', 'iName' =>'Calcium ascorbate', 'iType' => 1, 'eNumber' => 'E302', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '120', 'iName' =>'Ascorbyl palmitate', 'iType' => 1, 'eNumber' => 'E304', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '121', 'iName' =>'Tocopherol', 'iType' => 1, 'eNumber' => 'E306', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '122', 'iName' =>'Tocopherol', 'iType' => 1, 'eNumber' => 'E307', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '123', 'iName' =>'Gamma-Tocopherol', 'iType' => 1, 'eNumber' => 'E308', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '124', 'iName' =>'Delta-Tocopherol', 'iType' => 1, 'eNumber' => 'E309', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '125', 'iName' =>'Propyl gallate', 'iType' => 1, 'eNumber' => 'E310', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '126', 'iName' =>'Octyl gallate', 'iType' => 1, 'eNumber' => 'E311', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '127', 'iName' =>'Dodecyl gallate', 'iType' => 1, 'eNumber' => 'E312', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '128', 'iName' =>'Erythorbic acid', 'iType' => 1, 'eNumber' => 'E315', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '129', 'iName' =>'Sodium erythorbate', 'iType' => 1, 'eNumber' => 'E316', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '130', 'iName' =>'Tert-Butylhydroquinone', 'iType' => 1, 'eNumber' => 'E319', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '131', 'iName' =>'Butylated hydroxyanisole', 'iType' => 1, 'eNumber' => 'E320', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '132', 'iName' =>'Butylated hydroxytoluene', 'iType' => 1, 'eNumber' => 'E321', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '133', 'iName' =>'Lecithin', 'iType' => 1, 'eNumber' => 'E322', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '134', 'iName' =>'Sodium lactate', 'iType' => 1, 'eNumber' => 'E325', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '135', 'iName' =>'Potassium lactate', 'iType' => 1, 'eNumber' => 'E326', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '136', 'iName' =>'Calcium lactate', 'iType' => 1, 'eNumber' => 'E327', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '137', 'iName' =>'Citric acid', 'iType' => 1, 'eNumber' => 'E330', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '138', 'iName' =>'Sodium citrate', 'iType' => 1, 'eNumber' => 'E331', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '139', 'iName' =>'Potassium citrate', 'iType' => 1, 'eNumber' => 'E332', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '140', 'iName' =>'Calcium citrate', 'iType' => 1, 'eNumber' => 'E333', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '141', 'iName' =>'Tartaric acid', 'iType' => 1, 'eNumber' => 'E334', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '142', 'iName' =>'Sodium tartrate', 'iType' => 1, 'eNumber' => 'E335', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '143', 'iName' =>'Potassium tartrate', 'iType' => 1, 'eNumber' => 'E336', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '144', 'iName' =>'Potassium sodium tartrate', 'iType' => 1, 'eNumber' => 'E337', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '145', 'iName' =>'Phosphoric acid', 'iType' => 1, 'eNumber' => 'E338', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '146', 'iName' =>'Trisodium phosphate', 'iType' => 1, 'eNumber' => 'E339', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '147', 'iName' =>'Potassium phosphate', 'iType' => 1, 'eNumber' => 'E340', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '148', 'iName' =>'Calcium phosphate', 'iType' => 1, 'eNumber' => 'E341', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '149', 'iName' =>'Magnesium phosphate', 'iType' => 1, 'eNumber' => 'E343', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '150', 'iName' =>'Sodium malate', 'iType' => 1, 'eNumber' => 'E350', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '151', 'iName' =>'Potassium malate', 'iType' => 1, 'eNumber' => 'E351', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '152', 'iName' =>'Calcium malate', 'iType' => 1, 'eNumber' => 'E352', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '153', 'iName' =>'Metataric Acid', 'iType' => 1, 'eNumber' => 'E353', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '154', 'iName' =>'Calcium tartrate', 'iType' => 1, 'eNumber' => 'E354', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '155', 'iName' =>'Adipic acid', 'iType' => 1, 'eNumber' => 'E355', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '156', 'iName' =>'Sodium adipate', 'iType' => 1, 'eNumber' => 'E356', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '157', 'iName' =>'Potassium adipate', 'iType' => 1, 'eNumber' => 'E357', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '158', 'iName' =>'Succinic acid', 'iType' => 1, 'eNumber' => 'E363', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '159', 'iName' =>'Gamma-Butyrolactone', 'iType' => 1, 'eNumber' => 'E370', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '160', 'iName' =>'Niacin', 'iType' => 1, 'eNumber' => 'E375', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '161', 'iName' =>'Triammonium Citrate', 'iType' => 1, 'eNumber' => 'E380', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '162', 'iName' =>'Ammonium ferric citrate', 'iType' => 1, 'eNumber' => 'E381', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '163', 'iName' =>'Ethylenediaminetetraacetic acid', 'iType' => 1, 'eNumber' => 'E385', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '164', 'iName' =>'Alginic acid', 'iType' => 1, 'eNumber' => 'E400', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '165', 'iName' =>'Alginic acid', 'iType' => 1, 'eNumber' => 'E401', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '166', 'iName' =>'Potassium alginate', 'iType' => 1, 'eNumber' => 'E402', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '167', 'iName' =>'Ammonium Alginate', 'iType' => 1, 'eNumber' => 'E403', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '168', 'iName' =>'Calcium alginate', 'iType' => 1, 'eNumber' => 'E404', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '169', 'iName' =>'Propylene glycol alginate', 'iType' => 1, 'eNumber' => 'E405', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '170', 'iName' =>'Agar-agar', 'iType' => 1, 'eNumber' => 'E406', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '171', 'iName' =>'Carrageenan', 'iType' => 1, 'eNumber' => 'E407', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '172', 'iName' =>'Locust bean gum', 'iType' => 1, 'eNumber' => 'E410', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '173', 'iName' =>'Guar gum', 'iType' => 1, 'eNumber' => 'E412', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '174', 'iName' =>'Tragacanth', 'iType' => 1, 'eNumber' => 'E413', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '175', 'iName' =>'Gum arabic', 'iType' => 1, 'eNumber' => 'E414', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '176', 'iName' =>'Xanthan gum', 'iType' => 1, 'eNumber' => 'E415', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '177', 'iName' =>'Gum karaya', 'iType' => 1, 'eNumber' => 'E416', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '178', 'iName' =>'Tara gum', 'iType' => 1, 'eNumber' => 'E417', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '179', 'iName' =>'Gellan gum', 'iType' => 1, 'eNumber' => 'E418', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '180', 'iName' =>'Sorbitol', 'iType' => 1, 'eNumber' => 'E420', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '181', 'iName' =>'Mannitol', 'iType' => 1, 'eNumber' => 'E421', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '182', 'iName' =>'Glycerol', 'iType' => 1, 'eNumber' => 'E422', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '183', 'iName' =>'Konjac', 'iType' => 1, 'eNumber' => 'E425', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '184', 'iName' =>'Polyoxyethane (8) Stearate', 'iType' => 1, 'eNumber' => 'E430', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '185', 'iName' =>'Polyoxyethane (40) Stearate', 'iType' => 1, 'eNumber' => 'E431', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '186', 'iName' =>'Polysorbate 20', 'iType' => 1, 'eNumber' => 'E432', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '187', 'iName' =>'Polysorbate 80', 'iType' => 1, 'eNumber' => 'E433', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '188', 'iName' =>'Polysorbate 40', 'iType' => 1, 'eNumber' => 'E434', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '189', 'iName' =>'Polysorbate 60', 'iType' => 1, 'eNumber' => 'E435', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '190', 'iName' =>'Polysorbate 65', 'iType' => 1, 'eNumber' => 'E436', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '191', 'iName' =>'Pectin', 'iType' => 1, 'eNumber' => 'E440a', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '192', 'iName' =>'Amidated Pectin', 'iType' => 1, 'eNumber' => 'E440b', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '193', 'iName' =>'Gelatin', 'iType' => 1, 'eNumber' => 'E441', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '194', 'iName' =>'Ammonium phosphatides', 'iType' => 1, 'eNumber' => 'E442', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '195', 'iName' =>'Sucrose acetate isobutyrate', 'iType' => 1, 'eNumber' => 'E444', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '196', 'iName' =>'Glycerol esters of wood rosins', 'iType' => 1, 'eNumber' => 'E445', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '197', 'iName' =>'Pyrophosphate', 'iType' => 1, 'eNumber' => 'E450', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '198', 'iName' =>'Sodium triphosphate', 'iType' => 1, 'eNumber' => 'E451', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '199', 'iName' =>'Polyphosphate', 'iType' => 1, 'eNumber' => 'E452', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '200', 'iName' =>'Beta-cyclodextrin', 'iType' => 1, 'eNumber' => 'E459', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '201', 'iName' =>'Cellulose', 'iType' => 1, 'eNumber' => 'E460', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '202', 'iName' =>'Methylcellulose', 'iType' => 1, 'eNumber' => 'E461', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '203', 'iName' =>'Hydroxypropylcellulose', 'iType' => 1, 'eNumber' => 'E463', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '204', 'iName' =>'Hydroxypropyl methylcellulose', 'iType' => 1, 'eNumber' => 'E464', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '205', 'iName' =>'Ethyl methyl cellulose', 'iType' => 1, 'eNumber' => 'E465', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '206', 'iName' =>'Carboxymethyl cellulose', 'iType' => 1, 'eNumber' => 'E466', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '207', 'iName' =>'Ethyl hydroxyethyl cellulose', 'iType' => 1, 'eNumber' => 'E467', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '208', 'iName' =>'Crosslinked sodium carboxymethyl cellulose', 'iType' => 1, 'eNumber' => 'E468', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '209', 'iName' =>'Enzymically hydrolysed carboxymethylcellulose', 'iType' => 1, 'eNumber' => 'E469', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '210', 'iName' =>'Sodium, Potassium and Calcium Salts of Fatty Acids', 'iType' => 1, 'eNumber' => 'E470', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '211', 'iName' =>'Mono- and diglycerides of fatty acids', 'iType' => 1, 'eNumber' => 'E471', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '212', 'iName' =>'Various Esters of Mono-and Diglycerides of Fatty Acids', 'iType' => 1, 'eNumber' => 'E472', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '213', 'iName' =>'Di-acetyl tartrate ester of monoglyceride', 'iType' => 1, 'eNumber' => 'E472e', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '214', 'iName' =>'Sucrose esters of fatty acids', 'iType' => 1, 'eNumber' => 'E473', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '215', 'iName' =>'Sucroglycerides', 'iType' => 1, 'eNumber' => 'E474', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '216', 'iName' =>'Polyglycerol esters of fatty acids', 'iType' => 1, 'eNumber' => 'E475', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '217', 'iName' =>'Polyglycerol polyricinoleate', 'iType' => 1, 'eNumber' => 'E476', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '218', 'iName' =>'Propane-1,2-Diol Esters of Fatty Acids', 'iType' => 1, 'eNumber' => 'E477', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '219', 'iName' =>'Lactylated fatty acid esters of glycerol and propane-1', 'iType' => 1, 'eNumber' => 'E478', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '220', 'iName' =>'Thermally oxidized soya bean oil interacted with mono- and diglycerides of fatty acids', 'iType' => 1, 'eNumber' => 'E479b', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '221', 'iName' =>'Sodium stearoyl-2-lactylate', 'iType' => 1, 'eNumber' => 'E481', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '222', 'iName' =>'Calcium stearoyl-2-lactylate', 'iType' => 1, 'eNumber' => 'E482', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '223', 'iName' =>'Stearyl tartrate', 'iType' => 1, 'eNumber' => 'E483', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '224', 'iName' =>'Sorbitan monostearate', 'iType' => 1, 'eNumber' => 'E491', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '225', 'iName' =>'Sorbitan tristearate', 'iType' => 1, 'eNumber' => 'E492', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '226', 'iName' =>'Sorbitan monolaurate', 'iType' => 1, 'eNumber' => 'E493', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '227', 'iName' =>'Stearyl citrate', 'iType' => 1, 'eNumber' => 'E494', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '228', 'iName' =>'Sorbitan Monopalmitate', 'iType' => 1, 'eNumber' => 'E495', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '229', 'iName' =>'Sorbitan Trioleate', 'iType' => 1, 'eNumber' => 'E496', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '230', 'iName' =>'Sodium carbonate', 'iType' => 1, 'eNumber' => 'E500', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '231', 'iName' =>'Potassium carbonate', 'iType' => 1, 'eNumber' => 'E501', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '232', 'iName' =>'Ammonium carbonate', 'iType' => 1, 'eNumber' => 'E503', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '233', 'iName' =>'Magnesium carbonate', 'iType' => 1, 'eNumber' => 'E504', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '234', 'iName' =>'Hydrochloric acid', 'iType' => 1, 'eNumber' => 'E507', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '235', 'iName' =>'Potassium chloride', 'iType' => 1, 'eNumber' => 'E508', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '236', 'iName' =>'Calcium chloride', 'iType' => 1, 'eNumber' => 'E509', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '237', 'iName' =>'Ammonium chloride', 'iType' => 1, 'eNumber' => 'E510', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '238', 'iName' =>'Magnesium chloride', 'iType' => 1, 'eNumber' => 'E511', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '239', 'iName' =>'Stannous chloride', 'iType' => 1, 'eNumber' => 'E512', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '240', 'iName' =>'Sulphuric Acid', 'iType' => 1, 'eNumber' => 'E513', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '241', 'iName' =>'Sodium sulphate', 'iType' => 1, 'eNumber' => 'E514', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '242', 'iName' =>'Potassium sulphate', 'iType' => 1, 'eNumber' => 'E515', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '243', 'iName' =>'Calcium sulphate', 'iType' => 1, 'eNumber' => 'E516', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '244', 'iName' =>'Ammonium sulphate', 'iType' => 1, 'eNumber' => 'E517', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '245', 'iName' =>'Magnesium sulphate', 'iType' => 1, 'eNumber' => 'E518', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '246', 'iName' =>'Aluminium sulphate', 'iType' => 1, 'eNumber' => 'E520', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '247', 'iName' =>'Aluminium sodium sulphate', 'iType' => 1, 'eNumber' => 'E521', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '248', 'iName' =>'Aluminium potassium sulphate', 'iType' => 1, 'eNumber' => 'E522', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '249', 'iName' =>'Aluminium ammonium sulphate', 'iType' => 1, 'eNumber' => 'E523', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '250', 'iName' =>'Sodium hydroxide', 'iType' => 1, 'eNumber' => 'E524', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '251', 'iName' =>'Potassium hydroxide', 'iType' => 1, 'eNumber' => 'E525', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '252', 'iName' =>'Calcium hydroxide', 'iType' => 1, 'eNumber' => 'E526', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '253', 'iName' =>'Ammonium hydroxide', 'iType' => 1, 'eNumber' => 'E527', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '254', 'iName' =>'Magnesium hydroxide', 'iType' => 1, 'eNumber' => 'E528', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '255', 'iName' =>'Calcium oxide', 'iType' => 1, 'eNumber' => 'E529', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '256', 'iName' =>'Magnesium oxide', 'iType' => 1, 'eNumber' => 'E530', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '257', 'iName' =>'Sodium ferrocyanide', 'iType' => 1, 'eNumber' => 'E535', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '258', 'iName' =>'Potassium ferrocyanide', 'iType' => 1, 'eNumber' => 'E536', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '259', 'iName' =>'Calcium Ferrocyanide', 'iType' => 1, 'eNumber' => 'E538', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '260', 'iName' =>'Dicalcium Ferrocyanide', 'iType' => 1, 'eNumber' => 'E540', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '261', 'iName' =>'Sodium aluminium phosphate', 'iType' => 1, 'eNumber' => 'E541', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '262', 'iName' =>'Bone Phosphate', 'iType' => 1, 'eNumber' => 'E542', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '263', 'iName' =>'Calcium Polyphosphates', 'iType' => 1, 'eNumber' => 'E544', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '264', 'iName' =>'Ammonium polyphosphate', 'iType' => 1, 'eNumber' => 'E545', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '265', 'iName' =>'Sodium silicate', 'iType' => 1, 'eNumber' => 'E550', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '266', 'iName' =>'Silicon dioxide', 'iType' => 1, 'eNumber' => 'E551', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '267', 'iName' =>'Calcium silicate', 'iType' => 1, 'eNumber' => 'E552', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '268', 'iName' =>'Magnesium silicate', 'iType' => 1, 'eNumber' => 'E553', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '269', 'iName' =>'Sodium aluminosilicate', 'iType' => 1, 'eNumber' => 'E554', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '270', 'iName' =>'Potassium aluminium silicate', 'iType' => 1, 'eNumber' => 'E555', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '271', 'iName' =>'Calcium aluminosilicate', 'iType' => 1, 'eNumber' => 'E556', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '272', 'iName' =>'Bentonite', 'iType' => 1, 'eNumber' => 'E558', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '273', 'iName' =>'Aluminium silicate', 'iType' => 1, 'eNumber' => 'E559', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '274', 'iName' =>'Stearic acid', 'iType' => 1, 'eNumber' => 'E570', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '275', 'iName' =>'Magnesium stearate', 'iType' => 1, 'eNumber' => 'E572', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '276', 'iName' =>'Gluconic acid', 'iType' => 1, 'eNumber' => 'E574', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '277', 'iName' =>'Glucono delta-lactone', 'iType' => 1, 'eNumber' => 'E575', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '278', 'iName' =>'Sodium gluconate', 'iType' => 1, 'eNumber' => 'E576', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '279', 'iName' =>'Potassium gluconate', 'iType' => 1, 'eNumber' => 'E577', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '280', 'iName' =>'Calcium gluconate', 'iType' => 1, 'eNumber' => 'E578', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '281', 'iName' =>'Ferrous lactate', 'iType' => 1, 'eNumber' => 'E585', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '282', 'iName' =>'Glutamic acid', 'iType' => 1, 'eNumber' => 'E620', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '283', 'iName' =>'Monosodium glutamate', 'iType' => 1, 'eNumber' => 'E621', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '284', 'iName' =>'Monopotassium glutamate', 'iType' => 1, 'eNumber' => 'E622', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '285', 'iName' =>'Calcium glutamate', 'iType' => 1, 'eNumber' => 'E623', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '286', 'iName' =>'Monoammonium glutamate', 'iType' => 1, 'eNumber' => 'E624', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '287', 'iName' =>'Magnesium diglutamate', 'iType' => 1, 'eNumber' => 'E625', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '288', 'iName' =>'Guanylic acid', 'iType' => 1, 'eNumber' => 'E626', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '289', 'iName' =>'Disodium guanylate', 'iType' => 1, 'eNumber' => 'E627', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '290', 'iName' =>'Dipotassium guanylate', 'iType' => 1, 'eNumber' => 'E628', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '291', 'iName' =>'Calcium guanylate', 'iType' => 1, 'eNumber' => 'E629', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '292', 'iName' =>'Inosinic acid', 'iType' => 1, 'eNumber' => 'E630', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '293', 'iName' =>'Sodium inosinate', 'iType' => 1, 'eNumber' => 'E631', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '294', 'iName' =>'Dipotassium inosinate', 'iType' => 1, 'eNumber' => 'E632', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '295', 'iName' =>'Calcium inosinate', 'iType' => 1, 'eNumber' => 'E633', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '296', 'iName' =>'Calcium5-Ribonucleotide', 'iType' => 1, 'eNumber' => 'E634', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '297', 'iName' =>'Disodium 5-ribonucleotides', 'iType' => 1, 'eNumber' => 'E635', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '298', 'iName' =>'Maltol', 'iType' => 1, 'eNumber' => 'E636', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '299', 'iName' =>'Ethyl maltol', 'iType' => 1, 'eNumber' => 'E637', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '300', 'iName' =>'Glycine', 'iType' => 1, 'eNumber' => 'E640', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '301', 'iName' =>'Zinc acetate', 'iType' => 1, 'eNumber' => 'E650', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '302', 'iName' =>'Dimethylpolysiloxane', 'iType' => 1, 'eNumber' => 'E900', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '303', 'iName' =>'Beeswax', 'iType' => 1, 'eNumber' => 'E901', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '304', 'iName' =>'Candelilla wax', 'iType' => 1, 'eNumber' => 'E902', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '305', 'iName' =>'Carnauba wax', 'iType' => 1, 'eNumber' => 'E903', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '306', 'iName' =>'Shellac', 'iType' => 1, 'eNumber' => 'E904', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '307', 'iName' =>'Mineral oil', 'iType' => 1, 'eNumber' => 'E905', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '308', 'iName' =>'Crystalline wax', 'iType' => 1, 'eNumber' => 'E907', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '309', 'iName' =>'Montanic acid', 'iType' => 1, 'eNumber' => 'E912', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '310', 'iName' =>'Lanolin', 'iType' => 1, 'eNumber' => 'E913', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '311', 'iName' =>'Oxidised Polyethylene wax', 'iType' => 1, 'eNumber' => 'E914', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '312', 'iName' =>'L-cysteine', 'iType' => 1, 'eNumber' => 'E920', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '313', 'iName' =>'Potassium bromate', 'iType' => 1, 'eNumber' => 'E924', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '314', 'iName' =>'Chlorine', 'iType' => 1, 'eNumber' => 'E925', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '315', 'iName' =>'Chlorine dioxide', 'iType' => 1, 'eNumber' => 'E926', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '316', 'iName' =>'Carbamide', 'iType' => 1, 'eNumber' => 'E927b', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '317', 'iName' =>'Argon', 'iType' => 1, 'eNumber' => 'E938', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '318', 'iName' =>'Helium', 'iType' => 1, 'eNumber' => 'E939', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '319', 'iName' =>'Nitrogen', 'iType' => 1, 'eNumber' => 'E941', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '320', 'iName' =>'Nitrous oxide', 'iType' => 1, 'eNumber' => 'E942', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '321', 'iName' =>'Butane', 'iType' => 1, 'eNumber' => 'E943a', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '322', 'iName' =>'Iso-butane', 'iType' => 1, 'eNumber' => 'E943b', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '323', 'iName' =>'Propane', 'iType' => 1, 'eNumber' => 'E944', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '324', 'iName' =>'Hydrogen', 'iType' => 1, 'eNumber' => 'E949', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '325', 'iName' =>'Aspartane', 'iType' => 1, 'eNumber' => 'E951', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '326', 'iName' =>'Isomalt', 'iType' => 1, 'eNumber' => 'E953', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '327', 'iName' =>'Saccharin', 'iType' => 1, 'eNumber' => 'E954', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '328', 'iName' =>'Maltitol', 'iType' => 1, 'eNumber' => 'E965', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '329', 'iName' =>'Lactitol', 'iType' => 1, 'eNumber' => 'E966', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '330', 'iName' =>'Xylitol', 'iType' => 1, 'eNumber' => 'E967', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '331', 'iName' =>'Erythritol', 'iType' => 1, 'eNumber' => 'E968', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '332', 'iName' =>'Quillaia extract', 'iType' => 1, 'eNumber' => 'E999', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '333', 'iName' =>'Whole Corn', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '334', 'iName' =>'Palm Oil', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '335', 'iName' =>'Flavour Enhacer', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '336', 'iName' =>'Rice', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '337', 'iName' =>'Corn', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '338', 'iName' =>'Dextrose', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '339', 'iName' =>'Vegetable Oil', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '340', 'iName' =>'Sugar', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '341', 'iName' =>'Soybean Powder', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '342', 'iName' =>'Whey Powder', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '343', 'iName' =>'Egg Powder', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '344', 'iName' =>'Salt', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '345', 'iName' =>'Water', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '346', 'iName' =>'Wheat Flour', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '347', 'iName' =>'Soya Lecithin', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '348', 'iName' =>'Chocolate Sraying', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '349', 'iName' =>'Chocolate Sraying', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '350', 'iName' =>'Skimmed Milk Powder', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '351', 'iName' =>'Glucose Syrup', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '352', 'iName' =>'Maltodextrine', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '353', 'iName' =>'Cocoa Powder', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '354', 'iName' =>'Emulsifier', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '355', 'iName' =>'White Chocolate', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '356', 'iName' =>'Milk Chocolate', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '357', 'iName' =>'Cream', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '358', 'iName' =>'Carcamine', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '359', 'iName' =>'Choco Chips', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '360', 'iName' =>'Margarine', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '361', 'iName' =>'Eggs', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '362', 'iName' =>'Sesame Seeds Peanuts', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '363', 'iName' =>'Treenuts', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '364', 'iName' =>'Skimmed Milk', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '365', 'iName' =>'Natural', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '366', 'iName' =>'Chocolate Extract', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '367', 'iName' =>'Chocolate Flavour', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '368', 'iName' =>'Fresh Milk', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '369', 'iName' =>'Vegetable Stabilizer', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '370', 'iName' =>'Chocolate Artificial Flavor', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '371', 'iName' =>'Orange Pulp', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '372', 'iName' =>'Orange Concentrate', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '373', 'iName' =>'Orange Flavour', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '374', 'iName' =>'Vitamin C', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '375', 'iName' =>'Non Diary Creamer', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '376', 'iName' =>'Instant Coffee', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '377', 'iName' =>'Artificial Sweetener Sucralose', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '378', 'iName' =>'Acesumfame-K', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '379', 'iName' =>'Mie', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '380', 'iName' =>'Tapioka', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '381', 'iName' =>'Sodium Poliphospate', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '382', 'iName' =>'Acidity Regulator', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '383', 'iName' =>'Chicken', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '384', 'iName' =>'Fungi', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '385', 'iName' =>'Onion', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '386', 'iName' =>'Soy Sauce', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '387', 'iName' =>'Sesame Oil', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '388', 'iName' =>'Pepper Powder', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '389', 'iName' =>'Chili', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '390', 'iName' =>'Cassava Powder', 'iType' => 0,'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '401', 'iName' =>'Curcumin', 'iType' => 1, 'eNumber' => 'E100', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '402', 'iName' =>'Peanuts', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '403', 'iName' =>'soya bean extract', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '404', 'iName' =>'stabilizer', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '405', 'iName' =>'artificial pandan flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '406', 'iName' =>'chocolate powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '407', 'iName' =>'milk powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '408', 'iName' =>'raising agent', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '409', 'iName' =>'nature identical vanilin flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '410', 'iName' =>'potato', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '411', 'iName' =>'seaweed flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '412', 'iName' =>'L Casei Shirota Strain', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '413', 'iName' =>'creamer', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '414', 'iName' =>'cacao powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '415', 'iName' =>'avocado identical flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '416', 'iName' =>'Milk', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '417', 'iName' =>'Vanilla', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '418', 'iName' =>'Coconut Oil', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '419', 'iName' =>'Omega 9', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '420', 'iName' =>'Omega 6', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '421', 'iName' =>'Vegetable Emulsifier', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '422', 'iName' =>'Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '423', 'iName' =>'Vitamins', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '424', 'iName' =>'Antioxidant Ascorbyl Palmitate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '425', 'iName' =>'Mixed Tocopherol', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '426', 'iName' =>'Sequestrant EDTA', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '427', 'iName' =>'Food Colouring Beta-carotene CI 40800', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '428', 'iName' =>'Food Stabilizer', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '429', 'iName' =>'Identical Mocca Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '430', 'iName' =>'Dextrosa', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '431', 'iName' =>'Whey Oil', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '432', 'iName' =>'Non Dairy Creamer', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '433', 'iName' =>'Chicken Meat', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '434', 'iName' =>'Breadcrumb', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '435', 'iName' =>'Battermix Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '436', 'iName' =>'Coriander Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '437', 'iName' =>'Omega 3', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '438', 'iName' =>'Chocolate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '439', 'iName' =>'Grapes Concentrate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '440', 'iName' =>'Aloe Vera', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '441', 'iName' =>'Spaghetti', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '442', 'iName' =>'Semolina Durum Wheat', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '443', 'iName' =>'Tomato Sauce', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '444', 'iName' =>'Salty Soy Sauce', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '445', 'iName' =>'Chicnken Broth', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '446', 'iName' =>'Mushroom', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '447', 'iName' =>'Sweet Soy Sauce', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '448', 'iName' =>'Tapioca', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '449', 'iName' =>'Flavour Enhancer', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '450', 'iName' =>'Red Onion', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '451', 'iName' =>'Garlic', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '452', 'iName' =>'Chili Sauce', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '453', 'iName' =>'Tapioca Starch', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '454', 'iName' =>'Vegetable Stabilizerand Sodium Polyphospate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '455', 'iName' =>'Antioxidant', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '456', 'iName' =>'Yeast Extract', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '457', 'iName' =>'Dried Vegetable', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '458', 'iName' =>'Onion Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '459', 'iName' =>'Hydrolised Vegetable Protein', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '460', 'iName' =>'Garlic Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '461', 'iName' =>'Flavor Enhancer', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '462', 'iName' =>'Anticacking', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '463', 'iName' =>'Nature Identical Chicken Flavor', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '464', 'iName' =>'Caramel Color IV', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '465', 'iName' =>'Skim Milk Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '466', 'iName' =>'Nature Identical Tiramisu Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '467', 'iName' =>'Bean', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '468', 'iName' =>'Dried Potato', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '469', 'iName' =>'Nata De Coco', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '470', 'iName' =>'Cocopandan Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '471', 'iName' =>'Sodium Benzoat', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '472', 'iName' =>'Tauco', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '473', 'iName' =>'Natrium Benzoat', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '474', 'iName' =>'Cassava', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '475', 'iName' =>'Glucose', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '476', 'iName' =>'Malt Extract', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '477', 'iName' =>'Yeast', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '478', 'iName' =>'Leavening Agent', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '479', 'iName' =>'Vitamin Premix B1', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '480', 'iName' =>'B2', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '481', 'iName' =>'B6', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '482', 'iName' =>'Konjac Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '483', 'iName' =>'Artificial Lychee Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '484', 'iName' =>'Sucrose', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '485', 'iName' =>'Buttermilk Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '486', 'iName' =>'Lactosa', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '487', 'iName' =>'Coffee Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '488', 'iName' =>'Ginger Extract', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '489', 'iName' =>'Chili Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '490', 'iName' =>'Oat Corn', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '491', 'iName' =>'Vitamin Premix', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '492', 'iName' =>'Vanili', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '493', 'iName' =>'Egg', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '494', 'iName' =>'Coconut', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '495', 'iName' =>'Edible Vegetable Oil', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '496', 'iName' =>'Thickener And Colouring', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '497', 'iName' =>'Nature Identical Tomato', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '498', 'iName' =>'Palm Sugar', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '499', 'iName' =>'Artificial Whiite Cappuccino Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '500', 'iName' =>'Annato', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '501', 'iName' =>'Vitamin A', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '502', 'iName' =>'Milk Solid', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '503', 'iName' =>'Cocoa Butter', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '504', 'iName' =>'Vegetable Fat', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '505', 'iName' =>'Emulsifiers', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '506', 'iName' =>'Premiks', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '507', 'iName' =>'Coconut Water', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '508', 'iName' =>'Nature Identical Coconut Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '509', 'iName' =>'Stabilizer Xanthan Gum', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '510', 'iName' =>'Durum Wheat Semolina', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '511', 'iName' =>'Strawbery Natural Identical Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '512', 'iName' =>'Raspbery Identical Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '513', 'iName' =>'Fine Granulated Sugar', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '514', 'iName' =>'Shortening', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '515', 'iName' =>'Baker\'s Yeast', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '516', 'iName' =>'Flour Treatment', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '517', 'iName' =>'Cashew', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '518', 'iName' =>'Cocoa Mass', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '519', 'iName' =>'Dark Chocolate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '520', 'iName' =>'Vegetable Protein', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '521', 'iName' =>'Chicken Broth', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '522', 'iName' =>'Red Chilli', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '523', 'iName' =>'Green Chilli', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '524', 'iName' =>'Coconut Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '525', 'iName' =>'Lecitin', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '526', 'iName' =>'Milk Cream', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '527', 'iName' =>'Mineral', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '528', 'iName' =>'Natrium Phosphat', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '529', 'iName' =>'Vegetable Creamer', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '530', 'iName' =>'Malt', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '531', 'iName' =>'Oat', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '532', 'iName' =>'Artificial Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '533', 'iName' =>'Ginger Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '534', 'iName' =>'Glycerin', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '535', 'iName' =>'High Fructose Corn Syrup', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '536', 'iName' =>'Preservative', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '537', 'iName' =>'Flavour And Flavouring', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '538', 'iName' =>'Hydrolized Milk Protein', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '539', 'iName' =>'Fructose Syrup', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '540', 'iName' =>'Soy Lecithin', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '541', 'iName' =>'Artificial Vanila Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '542', 'iName' =>'Gluten', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '543', 'iName' =>'Tapioca Flour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '544', 'iName' =>'Cashew Nut', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '545', 'iName' =>'Disodium Inosinate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '546', 'iName' =>'Corn Strach', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '547', 'iName' =>'Cheedar Cheese', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '548', 'iName' =>'Parsley', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '549', 'iName' =>'Sesame Seeds', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '550', 'iName' =>'Cheese', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '551', 'iName' =>'Seaweed', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '552', 'iName' =>'Dinatrium Inosinat', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '553', 'iName' =>'Soursop Puree', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '554', 'iName' =>'Sodium Chloride', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '555', 'iName' =>'Nature Identical Soursop Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '556', 'iName' =>'Orange Juice', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '557', 'iName' =>'Nature Identical Orange Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '558', 'iName' =>'Guava Puree', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '559', 'iName' =>'Nature Identical Guava Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '560', 'iName' =>'Cheese Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '561', 'iName' =>'Turmeric', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '562', 'iName' =>'Emulsifier Soy Lecithin', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '563', 'iName' =>'Vitamin B6', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '564', 'iName' =>'Preservative Sodium Benzoate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '565', 'iName' =>'Coconut Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '566', 'iName' =>'Calium Sorbate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '567', 'iName' =>'Shrimp Paste', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '568', 'iName' =>'Shallots', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '569', 'iName' =>'Alpha Tocoperol', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '570', 'iName' =>'Butter', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '571', 'iName' =>'Amonium Carbonate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '572', 'iName' =>'Nature Identical Flavour Banana', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '573', 'iName' =>'Nature Identical Flavour Milk', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '574', 'iName' =>'Banana Powder', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '575', 'iName' =>'Paprika Extract', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '576', 'iName' =>'Caramel', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '577', 'iName' =>'Mungbean Juice', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '578', 'iName' =>'Pandan Leaves', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '579', 'iName' =>'Ginger', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '580', 'iName' =>'Natural Colourant Caramel Class I-E150a', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '581', 'iName' =>'Soya Bean', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '582', 'iName' =>'Natrium Citrate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '583', 'iName' =>'Fructose', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '584', 'iName' =>'Ammonium Bicarbonate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '585', 'iName' =>'Sodium Bicarbonate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '586', 'iName' =>'Dessicated Coconut', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '587', 'iName' =>'Carbonate', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id' => '588', 'iName' =>'Artificial White Vanilla Fudgee Flavour', 'iType' => 1, 'eNumber' => NULL, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ];
    
        // masukkan data ke database
        DB::table('ingredients')->insert($ing);
    }
}